# 教程 https://docs.github.com/cn/actions/learn-github-actions/understanding-github-actions
# 语法 https://docs.github.com/cn/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
# action 标题
name: Puppeteer Screenshot

# 触发条件
on:
  push:
  # 定时执行，这里 - cron 配置的就是一个定期执行的表达式
  # 0 0,6,12,18 * * * 表示的在0，6，12，18点整点执行，这里是ISO时间，和国内差8小时
  # schedule:
  #   - cron: '0 0,6,12,18 * * *'

# 执行脚本定义
jobs:
  start:
    # 执行 运行器，可用 windows、ubuntu、macos
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'guchongxi/psa' }}
    # 执行步骤，串行 https://docs.github.com/cn/actions/using-workflows/workflow-syntax-for-github-actions#example-using-contexts
    steps:
      # 检出代码
      - uses: actions/checkout@v3
      # 因为执行的环境没有中文字体，抓中文网站会乱码，所以需要添加中文字体
      - name: Add chinese fonts
        # run是具体执行的内容，多行的话，需要有这么一个 '|'
        run: |
          sudo apt-get install ttf-mscorefonts-installer fontconfig
          fc-list :lang=zh
          cp -rf ./fonts/* /usr/share/fonts/
          mkfontscale
          mkfontdir
          fc-cache
          fc-list :lang=zh
      # 设置 node 环境为 14，默认是 16
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'
      # 安装依赖
      - name: Install
        run: yarn install --production
      # 执行脚本
      - name: Run script
        run: yarn start
      # 将新的截图用git提交到仓库中
      - name: Push snapshot
        run: |
          git config --global user.name 'guchongxi'
          git config --global user.email 'guchongxi@gmail.com'
          git add output/
          git commit -m "ci: push new snapshot"
          git pull --rebase
          git push
